name: Build Go app and push to Azure

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Paso 1: Clonar el repositorio
      - uses: actions/checkout@v3

      # Paso 2: Configurar Go
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23 # Cambiado a 1.20 para evitar problemas de compatibilidad

      # Paso 3: Verificar la versión de Go instalada
      - name: Check Go version
        run: go version

      # Paso 4: Instalar las dependencias
      - name: Install Dependencies
        run: |
          go mod tidy
          go mod download

      # Paso 5: Compilar la aplicación
      - name: Build
        run: go build -o build/bk-compras-extraordinarias.exe -v

      # Paso 6: Empaquetar la aplicación (incluyendo web.config)
      - name: Prepare deployment package
        run: |
          Compress-Archive -Path build\* -DestinationPath deployment-package.zip

      # Paso 7: Desplegar a Azure
      - name: Deploy to Azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: comprasExtraordinariasAPI # Nombre del Azure App Service
          package: deployment-package.zip
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
